#! /usr/bin/perl

use strict;
use warnings;

use 5.008;
use App::NoPAN;
use Getopt::Long;
use Pod::Usage;

our $VERSION = '0.01';

my %opts = (
    no_install => undef,
);
my ($opt_help, $opt_version);
GetOptions(
    help         => \$opt_help,
    version      => \$opt_version,
    'no-install' => sub { $opts{no_install} = 1 },
) or pod2usage(1);
if ($opt_help) {
    pod2usage(0);
} elsif ($opt_version) {
    print "$VERSION\n";
    exit 0;
}
die "no args"
    unless @ARGV;

my $nopan = App::NoPAN->new(%opts);
$nopan->install($_)
    for @ARGV;

__END__

=head1 NAME

nopan - download software from source-code repository and install

=head1 SYNOPSIS

  nopan http://svn-or-git-repository

=head1 DESCRIPTION

Nopan downloads software from a subversion repository or a git repository using HTTP, and automatically installs the software.

=head1 AUTHOR

Kazuho Oku
Copyright (C) 2010 Cybozu Labs, Inc.

=head1 LICENSE

BSD

=cut
